application: true-area-87212
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application
- url: /_ah/login_required
  script: do_openid_login.application